/* eslint-disable react-refresh/only-export-components */
import {
  createContext,
  type ReactNode,
  useCallback,
  useContext,
  useEffect,
  useRef,
  useState,
} from 'react'

// ==========================================
// YYC³ 全局状态管理 — Context API + localStorage
// Phase 4: + Realtime simulation, export utils, keyboard shortcuts
// ==========================================

/**
 * Unique identifier for each navigable page in the application.
 * Used by `AppContext` to track the currently active view.
 */
export type PageId =
  | 'dashboard'
  | 'chat'
  | 'clm'
  | 'aicall'
  | 'tools'
  | 'workflow'
  | 'insights'
  | 'settings'
  | 'logs'
  | 'forms'
  | 'contacts'
  | 'customerCare'
  | 'profile'
  | 'collab'
  // Platform Integration (平台集成)
  | 'paramSettings'
  | 'platformSettings'
  | 'wechatConfig'
  | 'channelCenter'
  | 'dataIntegration'
  // AI Marketing (智能营销)
  | 'marketingPlan'
  | 'promotionExec'
  | 'marketingAnalytics'
  | 'marketingAssets'
  | 'customerAcquisition'
  | 'brandMgmt'
  | 'intelligentOps'
  | 'platformHub'
  | 'aiCreativeTools'
  | 'aiMarketingEngine'
  | 'appOverview'
  | 'aiDecisionSupport'
  | 'nlpProcessing'
  // Quick Actions (一键操作)
  | 'quickActions'
  // Task Board (任务看板)
  | 'taskBoard'
  // Developer Workspace (开发工作台)
  | 'devWorkspace'
  // API Documentation (API文档)
  | 'apiDocs'
  // Finance Management (财务管理)
  | 'finance'
  // Salary System (薪资系统)
  | 'salary'
  // Supply Chain (供应链)
  | 'smartForm'
  | 'procurement'
  | 'inventory'

/**
 * Application display mode.
 * - `standalone`: Full-screen desktop layout with sidebar navigation.
 * - `widget`: Compact floating panel mode for embedding.
 */
export type AppMode = 'standalone' | 'widget'

/**
 * Visual theme configuration controlling cyberpunk effects intensity.
 * Each boolean toggle enables/disables a specific visual layer;
 * `neonIntensity` (0-100) scales the glow strength of all neon elements.
 */
export interface ThemeConfig {
  neonIntensity: number // 0-100
  scanlineEnabled: boolean
  glitchEnabled: boolean
  circuitGridEnabled: boolean
  dataFlowEnabled: boolean
  springAnimEnabled: boolean
  blurEnabled: boolean
}

const defaultTheme: ThemeConfig = {
  neonIntensity: 80,
  scanlineEnabled: true,
  glitchEnabled: true,
  circuitGridEnabled: true,
  dataFlowEnabled: true,
  springAnimEnabled: true,
  blurEnabled: true,
}

interface AppState {
  activePage: PageId
  appMode: AppMode
  sidebarPinned: boolean
  notifications: NotificationItem[]
  recentActivities: ActivityItem[]
  theme: ThemeConfig
  onboardingDone: boolean
  mobileSidebarOpen: boolean
}

/**
 * A single notification entry displayed in the notification drawer.
 * Notifications are generated by the realtime simulation or user actions.
 */
export interface NotificationItem {
  id: string
  title: string
  message: string
  type: 'info' | 'success' | 'warning' | 'error'
  color: string
  timestamp: Date
  read: boolean
}

/**
 * A single activity record shown in the activity feed and log page.
 * Activities are auto-generated by the realtime simulation system.
 */
export interface ActivityItem {
  id: string
  action: string
  target: string
  timestamp: Date
  type: 'customer' | 'call' | 'system' | 'ai'
  color: string
}

interface AppContextType extends AppState {
  setActivePage: (page: PageId) => void
  setAppMode: (mode: AppMode) => void
  setSidebarPinned: (pinned: boolean) => void
  addNotification: (n: Omit<NotificationItem, 'id' | 'timestamp' | 'read'>) => void
  markNotificationRead: (id: string) => void
  clearNotifications: () => void
  addActivity: (a: Omit<ActivityItem, 'id' | 'timestamp'>) => void
  unreadCount: number
  updateTheme: (partial: Partial<ThemeConfig>) => void
  resetTheme: () => void
  setOnboardingDone: (done: boolean) => void
  setMobileSidebarOpen: (open: boolean) => void
  neonAlpha: (base: number) => number // helper: scales alpha by neonIntensity
}

const STORAGE_KEY = 'yyc3_app_state'
const THEME_STORAGE_KEY = 'yyc3_theme'
const ONBOARDING_KEY = 'yyc3_onboarding_done'

// Serializable subset for localStorage
interface PersistedState {
  activePage: PageId
  appMode: AppMode
  sidebarPinned: boolean
}

function loadPersistedState(): Partial<PersistedState> {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    if (raw) {
      const parsed = JSON.parse(raw)
      return {
        activePage: parsed.activePage || 'dashboard',
        appMode: parsed.appMode || 'standalone',
        sidebarPinned: parsed.sidebarPinned ?? false,
      }
    }
  } catch {
    // ignore parse errors
  }
  return {}
}

function savePersistedState(state: PersistedState) {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(state))
  } catch {
    // ignore storage errors
  }
}

function loadTheme(): ThemeConfig {
  try {
    const raw = localStorage.getItem(THEME_STORAGE_KEY)
    if (raw) return { ...defaultTheme, ...JSON.parse(raw) }
  } catch {
    /* ignore */
  }
  return { ...defaultTheme }
}

function saveTheme(theme: ThemeConfig) {
  try {
    localStorage.setItem(THEME_STORAGE_KEY, JSON.stringify(theme))
  } catch {
    /* ignore */
  }
}

function loadOnboardingDone(): boolean {
  try {
    return localStorage.getItem(ONBOARDING_KEY) === 'true'
  } catch {
    return false
  }
}

// Mock initial notifications — title/message hold i18n keys; resolve via t() at render sites
const initialNotifications: NotificationItem[] = [
  {
    id: 'n1',
    title: 'ntf.n1.title',
    message: 'ntf.n1.message',
    type: 'success',
    color: '#00ffc8',
    timestamp: new Date(Date.now() - 300000),
    read: false,
  },
  {
    id: 'n2',
    title: 'ntf.n2.title',
    message: 'ntf.n2.message',
    type: 'info',
    color: '#00f0ff',
    timestamp: new Date(Date.now() - 1200000),
    read: false,
  },
  {
    id: 'n3',
    title: 'ntf.n3.title',
    message: 'ntf.n3.message',
    type: 'warning',
    color: '#00d4ff',
    timestamp: new Date(Date.now() - 2400000),
    read: false,
  },
  {
    id: 'n4',
    title: 'ntf.n4.title',
    message: 'ntf.n4.message',
    type: 'info',
    color: '#00f0ff',
    timestamp: new Date(Date.now() - 3600000),
    read: false,
  },
  {
    id: 'n5',
    title: 'ntf.n5.title',
    message: 'ntf.n5.message',
    type: 'success',
    color: '#00ffc8',
    timestamp: new Date(Date.now() - 5400000),
    read: true,
  },
  {
    id: 'n6',
    title: 'ntf.n6.title',
    message: 'ntf.n6.message',
    type: 'warning',
    color: '#00d4ff',
    timestamp: new Date(Date.now() - 7200000),
    read: true,
  },
  {
    id: 'n7',
    title: 'ntf.n7.title',
    message: 'ntf.n7.message',
    type: 'success',
    color: '#00ffc8',
    timestamp: new Date(Date.now() - 10800000),
    read: true,
  },
]

// Mock initial activities — action/target hold i18n keys; resolve via t() at render sites
const initialActivities: ActivityItem[] = [
  {
    id: 'a1',
    action: 'ntf.a1.action',
    target: 'ntf.a1.target',
    timestamp: new Date(Date.now() - 120000),
    type: 'ai',
    color: '#00d4ff',
  },
  {
    id: 'a2',
    action: 'ntf.a2.action',
    target: 'ntf.a2.target',
    timestamp: new Date(Date.now() - 600000),
    type: 'call',
    color: '#00ffcc',
  },
  {
    id: 'a3',
    action: 'ntf.a3.action',
    target: 'ntf.a3.target',
    timestamp: new Date(Date.now() - 1800000),
    type: 'customer',
    color: '#00f0ff',
  },
  {
    id: 'a4',
    action: 'ntf.a4.action',
    target: 'ntf.a4.target',
    timestamp: new Date(Date.now() - 3600000),
    type: 'system',
    color: '#00ffc8',
  },
  {
    id: 'a5',
    action: 'ntf.a5.action',
    target: 'ntf.a5.target',
    timestamp: new Date(Date.now() - 5400000),
    type: 'customer',
    color: '#00d4ff',
  },
  {
    id: 'a6',
    action: 'ntf.a6.action',
    target: 'ntf.a6.target',
    timestamp: new Date(Date.now() - 7200000),
    type: 'ai',
    color: '#00f0ff',
  },
]

const AppContext = createContext<AppContextType | null>(null)

/**
 * Root application state provider.
 * Manages page navigation, notifications, activities, theme config,
 * onboarding status, and mobile sidebar state.
 * Persists serializable subset to `localStorage`.
 */
export function AppProvider({ children }: { children: ReactNode }) {
  const persisted = loadPersistedState()

  const [activePage, setActivePageRaw] = useState<PageId>(persisted.activePage || 'dashboard')
  const [appMode, setAppModeRaw] = useState<AppMode>(persisted.appMode || 'standalone')
  const [sidebarPinned, setSidebarPinnedRaw] = useState(persisted.sidebarPinned ?? false)
  const [notifications, setNotifications] = useState<NotificationItem[]>(initialNotifications)
  const [recentActivities, setRecentActivities] = useState<ActivityItem[]>(initialActivities)
  const [theme, setTheme] = useState<ThemeConfig>(loadTheme)
  const [onboardingDone, setOnboardingDoneRaw] = useState(loadOnboardingDone)
  const [mobileSidebarOpen, setMobileSidebarOpen] = useState(false)

  // Persist state changes
  useEffect(() => {
    savePersistedState({ activePage, appMode, sidebarPinned })
  }, [activePage, appMode, sidebarPinned])

  // Persist theme changes
  useEffect(() => {
    saveTheme(theme)
  }, [theme])

  const setActivePage = useCallback((page: PageId) => {
    setActivePageRaw(page)
  }, [])

  const setAppMode = useCallback((mode: AppMode) => {
    setAppModeRaw(mode)
  }, [])

  const setSidebarPinned = useCallback((pinned: boolean) => {
    setSidebarPinnedRaw(pinned)
  }, [])

  const addNotification = useCallback((n: Omit<NotificationItem, 'id' | 'timestamp' | 'read'>) => {
    setNotifications((prev) => [
      {
        ...n,
        id: `n_${Date.now()}`,
        timestamp: new Date(),
        read: false,
      },
      ...prev,
    ])
  }, [])

  const markNotificationRead = useCallback((id: string) => {
    setNotifications((prev) => prev.map((n) => (n.id === id ? { ...n, read: true } : n)))
  }, [])

  const clearNotifications = useCallback(() => {
    setNotifications((prev) => prev.map((n) => ({ ...n, read: true })))
  }, [])

  const addActivity = useCallback((a: Omit<ActivityItem, 'id' | 'timestamp'>) => {
    setRecentActivities((prev) =>
      [
        {
          ...a,
          id: `a_${Date.now()}`,
          timestamp: new Date(),
        },
        ...prev,
      ].slice(0, 20),
    )
  }, [])

  const updateTheme = useCallback((partial: Partial<ThemeConfig>) => {
    setTheme((prev) => ({ ...prev, ...partial }))
  }, [])

  const resetTheme = useCallback(() => {
    setTheme({ ...defaultTheme })
  }, [])

  const setOnboardingDone = useCallback((done: boolean) => {
    setOnboardingDoneRaw(done)
    try {
      localStorage.setItem(ONBOARDING_KEY, String(done))
    } catch {
      /* ignore */
    }
  }, [])

  const neonAlpha = useCallback(
    (base: number) => {
      return base * (theme.neonIntensity / 100)
    },
    [theme.neonIntensity],
  )

  const unreadCount = notifications.filter((n) => !n.read).length

  return (
    <AppContext.Provider
      value={{
        activePage,
        appMode,
        sidebarPinned,
        notifications,
        recentActivities,
        theme,
        onboardingDone,
        mobileSidebarOpen,
        setActivePage,
        setAppMode,
        setSidebarPinned,
        addNotification,
        markNotificationRead,
        clearNotifications,
        addActivity,
        unreadCount,
        updateTheme,
        resetTheme,
        setOnboardingDone,
        setMobileSidebarOpen,
        neonAlpha,
      }}
    >
      {children}
    </AppContext.Provider>
  )
}

/**
 * Hook to access the global application state and dispatch actions.
 * Must be called within an `<AppProvider>` tree.
 *
 * @throws Error if called outside of `AppProvider`.
 */
export function useApp() {
  const ctx = useContext(AppContext)
  if (!ctx) throw new Error('useApp must be used within AppProvider')
  return ctx
}

// ==========================================
// Realtime Simulation Hook — Phase 4
// Simulates WebSocket-like data pushes
// ==========================================

// Pool entries hold i18n keys in title/message; resolved via t() at render sites
const realtimeNotifPool: Array<Omit<NotificationItem, 'id' | 'timestamp' | 'read'>> = [
  {
    title: 'ntf.r1.title',
    message: 'ntf.r1.message',
    type: 'info',
    color: '#00f0ff',
  },
  {
    title: 'ntf.r2.title',
    message: 'ntf.r2.message',
    type: 'success',
    color: '#00ffc8',
  },
  {
    title: 'ntf.r3.title',
    message: 'ntf.r3.message',
    type: 'warning',
    color: '#00d4ff',
  },
  {
    title: 'ntf.r4.title',
    message: 'ntf.r4.message',
    type: 'success',
    color: '#00ffc8',
  },
  {
    title: 'ntf.r5.title',
    message: 'ntf.r5.message',
    type: 'info',
    color: '#00f0ff',
  },
  {
    title: 'ntf.r6.title',
    message: 'ntf.r6.message',
    type: 'success',
    color: '#00ffc8',
  },
  {
    title: 'ntf.r7.title',
    message: 'ntf.r7.message',
    type: 'error',
    color: '#005f73',
  },
  {
    title: 'ntf.r8.title',
    message: 'ntf.r8.message',
    type: 'success',
    color: '#00ffc8',
  },
]

// Pool entries hold i18n keys in action/target; resolved via t() at render sites
const realtimeActivityPool: Array<Omit<ActivityItem, 'id' | 'timestamp'>> = [
  { action: 'ntf.ra1.action', target: 'ntf.ra1.target', type: 'call', color: '#00ffcc' },
  { action: 'ntf.ra2.action', target: 'ntf.ra2.target', type: 'customer', color: '#00f0ff' },
  { action: 'ntf.ra3.action', target: 'ntf.ra3.target', type: 'ai', color: '#00d4ff' },
  { action: 'ntf.ra4.action', target: 'ntf.ra4.target', type: 'system', color: '#00ffc8' },
  { action: 'ntf.ra5.action', target: 'ntf.ra5.target', type: 'ai', color: '#00d4ff' },
  { action: 'ntf.ra6.action', target: 'ntf.ra6.target', type: 'customer', color: '#00f0ff' },
  { action: 'ntf.ra7.action', target: 'ntf.ra7.target', type: 'call', color: '#00ffcc' },
  { action: 'ntf.ra8.action', target: 'ntf.ra8.target', type: 'system', color: '#00ffc8' },
]

/**
 * Simulates WebSocket-like realtime data pushes.
 * Periodically injects notifications (every 15-25 s) and activities
 * (every 8-15 s) from a rotating pool of mock data.
 */
// E2E 构建标识:webServer 以 VITE_E2E=true 构建(生产 bundle + preview),
// 不能依赖 DEV 门控(生产构建恒为 false)
const E2E_MODE = import.meta.env.VITE_E2E === 'true'

/**
 * 假实时数据(KPI 随机波动 / 通知活动流)启用开关。
 *
 * 语义:
 * - E2E 测试一律关闭(定时重渲染会让 motion 动画节点在 CI 慢机上不稳定);
 * - 生产构建默认关闭——公网用户不应把随机演示数据误认为真实业务数据;
 * - DEV 默认开启(本地开发可见实时效果);
 * - 若需在生产/预览环境展示演示效果,显式设置 VITE_ENABLE_MOCK=true。
 *
 * 见审计报告 F-02(2026-09-26):此前仅以 E2E_MODE 门控,导致生产持续运行假数据。
 */
export const MOCK_REALTIME_ENABLED =
  !E2E_MODE && (import.meta.env.DEV || import.meta.env.VITE_ENABLE_MOCK === 'true')

export function useRealtimeSimulation() {
  const { addNotification, addActivity } = useApp()
  const notifIdxRef = useRef(0)
  const actIdxRef = useRef(0)

  useEffect(() => {
    // 仅 DEV 或显式 VITE_ENABLE_MOCK 时注入假数据;生产默认关闭,
    // 避免公网用户把随机演示数据误认为真实业务数据。
    // E2E 同样关闭(MOCK_REALTIME_ENABLED 已含 !E2E_MODE)。
    if (!MOCK_REALTIME_ENABLED) return
    // Push a random notification every 15-25s
    const notifTimer = setInterval(
      () => {
        const item = realtimeNotifPool[notifIdxRef.current % realtimeNotifPool.length]
        addNotification(item)
        notifIdxRef.current++
      },
      15000 + Math.random() * 10000,
    )

    // Push a random activity every 8-15s
    const actTimer = setInterval(
      () => {
        const item = realtimeActivityPool[actIdxRef.current % realtimeActivityPool.length]
        addActivity(item)
        actIdxRef.current++
      },
      8000 + Math.random() * 7000,
    )

    return () => {
      clearInterval(notifTimer)
      clearInterval(actTimer)
    }
  }, [addNotification, addActivity])
}

// ==========================================
// KPI Realtime Fluctuation Hook — Phase 4
// Returns slightly fluctuating metric values
// ==========================================

/**
 * Live KPI data structure returned by {@link useLiveKPI}.
 * Values fluctuate slightly every 5 seconds to simulate realtime updates.
 */
export interface LiveKPI {
  customers: number
  calls: number
  aiTasks: number
  responseMs: number
  refreshKey: number // increments on each update for animation trigger
}

/**
 * Hook returning slightly fluctuating KPI metrics, updating every 5 s.
 * Useful for dashboard live counters and sparkline animations.
 */
export function useLiveKPI(): LiveKPI {
  const [kpi, setKpi] = useState<LiveKPI>({
    customers: 1388,
    calls: 247,
    aiTasks: 1892,
    responseMs: 12,
    refreshKey: 0,
  })

  useEffect(() => {
    if (!MOCK_REALTIME_ENABLED) return // 生产默认关闭假 KPI 波动;DEV/VITE_ENABLE_MOCK 才运行
    const timer = setInterval(() => {
      setKpi((prev) => ({
        customers: prev.customers + Math.floor(Math.random() * 3) - (Math.random() > 0.7 ? 1 : 0),
        calls: prev.calls + Math.floor(Math.random() * 4),
        aiTasks: prev.aiTasks + Math.floor(Math.random() * 8) + 1,
        responseMs: Math.max(8, Math.min(18, prev.responseMs + (Math.random() > 0.5 ? 1 : -1))),
        refreshKey: prev.refreshKey + 1,
      }))
    }, 5000)
    return () => clearInterval(timer)
  }, [])

  return kpi
}

// ==========================================
// Export Data Utilities — Phase 4
// ==========================================

/**
 * Metadata describing a dataset available for CSV/JSON export.
 * Used by the `DataExportModal` to render selection UI.
 */
export interface ExportableDataset {
  id: string
  label: string
  description: string
  color: string
  rowCount: number
  fields: string[]
  getData: () => Record<string, unknown>[]
}

// 阶段 / 相对时间为显示文本,存 i18n 键;姓名/公司为 mock 专名保持原样
const mockCustomerExport = () => [
  {
    姓名: '张明远',
    公司: '星际科技',
    阶段: 'app.stage.conversion',
    价值: '¥128,000',
    健康度: 92,
    最近联系: 'app.time.2hAgo',
  },
  {
    姓名: '李思琪',
    公司: '云端数据',
    阶段: 'app.stage.deal',
    价值: '¥256,000',
    健康度: 88,
    最近联系: 'app.time.1dAgo',
  },
  {
    姓名: '王建华',
    公司: '量子计算',
    阶段: 'app.stage.acquisition',
    价值: '¥64,000',
    健康度: 65,
    最近联系: 'app.time.3dAgo',
  },
  {
    姓名: '陈雅文',
    公司: '智链网络',
    阶段: 'app.stage.service',
    价值: '¥512,000',
    健康度: 95,
    最近联系: 'app.time.justNow',
  },
  {
    姓名: '赵鹏飞',
    公司: '未来能源',
    阶段: 'app.stage.loyalty',
    价值: '¥1,024,000',
    健康度: 98,
    最近联系: 'app.time.5hAgo',
  },
  {
    姓名: '刘晓东',
    公司: '芯片科技',
    阶段: 'app.stage.acquisition',
    价值: '¥42,000',
    健康度: 70,
    最近联系: 'app.time.justNow',
  },
  {
    姓名: '周婷',
    公司: '银河传媒',
    阶段: 'app.stage.conversion',
    价值: '¥186,000',
    健康度: 82,
    最近联系: 'app.time.30minAgo',
  },
  {
    姓名: '马浩然',
    公司: '极光数据',
    阶段: 'app.stage.acquisition',
    价值: '¥88,000',
    健康度: 75,
    最近联系: 'app.time.1hAgo',
  },
]

// Mock Dashboard Export Data (Weekly Metrics) — 日期为显示文本,存 i18n 键
const mockDashboardExport = () => [
  { 日期: 'app.day.mon', 新客户: 42, 呼叫数: 35, AI任务: 128, 转化率: '38.2%' },
  { 日期: 'app.day.tue', 新客户: 56, 呼叫数: 48, AI任务: 156, 转化率: '41.5%' },
  { 日期: 'app.day.wed', 新客户: 38, 呼叫数: 32, AI任务: 112, 转化率: '35.8%' },
  { 日期: 'app.day.thu', 新客户: 67, 呼叫数: 58, AI任务: 189, 转化率: '44.2%' },
  { 日期: 'app.day.fri', 新客户: 72, 呼叫数: 64, AI任务: 201, 转化率: '47.1%' },
  { 日期: 'app.day.sat', 新客户: 45, 呼叫数: 28, AI任务: 95, 转化率: '33.9%' },
  { 日期: 'app.day.sun', 新客户: 52, 呼叫数: 42, AI任务: 167, 转化率: '40.6%' },
]

// 类型 / 状态为显示文本,存 i18n 键;姓名/公司为 mock 专名保持原样
const mockCallExport = () => [
  {
    姓名: '张明远',
    公司: '星际科技',
    类型: 'app.callType.outbound',
    状态: 'app.callStatus.done',
    时长: '2:34',
    AI评分: 92,
  },
  {
    姓名: '李思琪',
    公司: '云端数据',
    类型: 'app.callType.followup',
    状态: 'app.callStatus.waiting',
    时长: '--',
    AI评分: 85,
  },
  {
    姓名: '王建华',
    公司: '量子计算',
    类型: 'app.callType.transfer',
    状态: 'app.callStatus.queued',
    时长: '--',
    AI评分: 67,
  },
  {
    姓名: '陈雅文',
    公司: '智链网络',
    类型: 'app.callType.callback',
    状态: 'app.callStatus.done',
    时长: '6:12',
    AI评分: 96,
  },
  {
    姓名: '赵鹏飞',
    公司: '未来能源',
    类型: 'app.callType.outbound',
    状态: 'app.callStatus.done',
    时长: '3:45',
    AI评分: 88,
  },
]

/** Pre-configured exportable datasets covering dashboard, customer, and call data.
 *  label/description hold i18n keys; resolved via t() at render sites.
 *  `fields` stays as-is: it is the export file schema (CSV column headers), not UI copy. */
export const exportableDatasets: ExportableDataset[] = [
  {
    id: 'dashboard',
    label: 'ntf.ds1.label',
    description: 'ntf.ds1.description',
    color: '#00f0ff',
    rowCount: 7,
    fields: ['日期', '新客户', '呼叫数', 'AI任务', '转化率'],
    getData: mockDashboardExport,
  },
  {
    id: 'customers',
    label: 'ntf.ds2.label',
    description: 'ntf.ds2.description',
    color: '#00d4ff',
    rowCount: 8,
    fields: ['姓名', '公司', '阶段', '价值', '健康度', '最近联系'],
    getData: mockCustomerExport,
  },
  {
    id: 'calls',
    label: 'ntf.ds3.label',
    description: 'ntf.ds3.description',
    color: '#00ffcc',
    rowCount: 5,
    fields: ['姓名', '公司', '类型', '状态', '时长', 'AI评分'],
    getData: mockCallExport,
  },
]

/**
 * Exports an array of records as a UTF-8 BOM CSV file download.
 *
 * @param data - Array of flat key-value objects to serialize.
 * @param filename - Download filename without extension (`.csv` is appended).
 */
export function exportToCSV(data: Record<string, unknown>[], filename: string): void {
  if (!data.length) return
  const headers = Object.keys(data[0])
  const csvRows = [
    headers.join(','),
    ...data.map((row) =>
      headers
        .map((h) => {
          const val = String(row[h] ?? '')
          return val.includes(',') || val.includes('"') ? `"${val.replace(/"/g, '""')}"` : val
        })
        .join(','),
    ),
  ]
  const blob = new Blob(['\uFEFF' + csvRows.join('\n')], { type: 'text/csv;charset=utf-8' })
  downloadBlob(blob, `${filename}.csv`)
}

/**
 * Exports an array of records as a pretty-printed JSON file download.
 *
 * @param data - Array of objects to serialize.
 * @param filename - Download filename without extension (`.json` is appended).
 */
export function exportToJSON(data: Record<string, unknown>[], filename: string): void {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })
  downloadBlob(blob, `${filename}.json`)
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
