import re

zh_content = open('/Users/yanyu/YYC-Cube/YYC3-Administration/src/app/locales/zh.ts', 'r', encoding='utf-8').read()
en_content = open('/Users/yanyu/YYC-Cube/YYC3-Administration/src/app/locales/en.ts', 'r', encoding='utf-8').read()

zh_keys = '''
  // ---- Procurement (prc) ----
  'prc.title': '采购管理',
  'prc.desc': '供应商管理 · 采购申请 · 审批流程 · 采购订单 · 合同管理',
  'prc.aiAnalyze': 'AI 智能分析',
  'prc.newOrder': '新建采购单',
  'prc.stat.activeSuppliers': '活跃供应商',
  'prc.stat.pendingOrders': '待处理订单',
  'prc.stat.monthlySpend': '月度采购额',
  'prc.stat.onTimeRate': '准时交付率',
  'prc.stable': '稳定',
  'prc.stat.needAttention': '需关注',
  'prc.cat.overview': '概览',
  'prc.cat.suppliers': '供应商',
  'prc.cat.orders': '采购订单',
  'prc.cat.contracts': '合同管理',
  'prc.aiInsights': 'AI 智能洞察',
  'prc.ai.riskAlert': '供应风险预警',
  'prc.ai.riskAlertDesc': '恒达化工原料评级下降，建议评估替代供应商',
  'prc.ai.costOpt': '成本优化建议',
  'prc.ai.costOptDesc': '电子元件批量采购可节省约12%成本，建议合并订单',
  'prc.ai.supplierRec': '供应商推荐',
  'prc.ai.supplierRecDesc': '基于历史数据推荐3家优质供应商，评分均>4.5',
  'prc.recentOrders': '最近采购订单',
  'prc.viewAll': '查看全部',
  'prc.active': '活跃',
  'prc.pending': '待审核',
  'prc.suspended': '已暂停',
  'prc.approved': '已审批',
  'prc.inProgress': '进行中',
  'prc.completed': '已完成',
  'prc.rejected': '已驳回',
  'prc.searchSupplier': '搜索供应商...',
  'prc.rating': '评分',
  'prc.orders': '笔订单',
  'prc.highPriority': '高优先级',
  'prc.contractsComingSoon': '合同管理功能即将上线',
  'prc.contractsComingSoonDesc': 'AI合同审查、电子签章、履约跟踪等高级功能正在开发中',

  // ---- Inventory (inv) ----
  'inv.title': '库存管理',
  'inv.desc': '库存盘点 · 出入库管理 · 库存预警 · 批次追踪 · 仓库管理',
  'inv.aiRestock': 'AI 智能补货',
  'inv.newRecord': '新增出入库',
  'inv.stat.totalSku': 'SKU 总数',
  'inv.stat.lowStockAlerts': '低库存预警',
  'inv.stat.totalValue': '库存总价值',
  'inv.stat.turnoverRate': '库存周转率',
  'inv.stat.needAttention': '需关注',
  'inv.cat.overview': '概览',
  'inv.cat.stockList': '库存清单',
  'inv.cat.inOutRecords': '出入库记录',
  'inv.cat.warehouses': '仓库管理',
  'inv.aiInsights': 'AI 智能洞察',
  'inv.ai.restockAlert': '智能补货提醒',
  'inv.ai.restockAlertDesc': 'MCU控制芯片STM32库存低于安全库存，建议立即补货500片',
  'inv.ai.slowMoving': '呆滞库存预警',
  'inv.ai.slowMovingDesc': '防静电包装袋库存周转天数超过90天，建议促销或退货',
  'inv.ai.turnoverOpt': '周转率优化',
  'inv.ai.turnoverOptDesc': '整体库存周转率3.8x，目标优化至4.5x，建议调整采购节奏',
  'inv.stockAlerts': '库存预警',
  'inv.viewAll': '查看全部',
  'inv.normal': '正常',
  'inv.low': '库存偏低',
  'inv.outOfStock': '缺货',
  'inv.overstock': '库存过剩',
  'inv.safetyStock': '安全库存',
  'inv.searchItem': '搜索物料名称/SKU...',
  'inv.in': '入库',
  'inv.out': '出库',
  'inv.operator': '操作人',
  'inv.warehousesComingSoon': '仓库管理功能即将上线',
  'inv.warehousesComingSoonDesc': '多仓库联动、库位管理、RFID追踪等高级功能正在开发中',

  // ---- Navigation (nav) ----
  'nav.procurement': '采购管理',
  'nav.inventory': '库存管理',
'''

en_keys = '''
  // ---- Procurement (prc) ----
  'prc.title': 'Procurement Management',
  'prc.desc': 'Supplier Management · Purchase Requests · Approval · Orders · Contracts',
  'prc.aiAnalyze': 'AI Analysis',
  'prc.newOrder': 'New Order',
  'prc.stat.activeSuppliers': 'Active Suppliers',
  'prc.stat.pendingOrders': 'Pending Orders',
  'prc.stat.monthlySpend': 'Monthly Spend',
  'prc.stat.onTimeRate': 'On-Time Rate',
  'prc.stable': 'Stable',
  'prc.stat.needAttention': 'Needs Attention',
  'prc.cat.overview': 'Overview',
  'prc.cat.suppliers': 'Suppliers',
  'prc.cat.orders': 'Orders',
  'prc.cat.contracts': 'Contracts',
  'prc.aiInsights': 'AI Insights',
  'prc.ai.riskAlert': 'Supply Risk Alert',
  'prc.ai.riskAlertDesc': 'Hengda Chemical rating declined, recommend evaluating alternative suppliers',
  'prc.ai.costOpt': 'Cost Optimization',
  'prc.ai.costOptDesc': 'Bulk purchasing electronic components can save ~12%, recommend merging orders',
  'prc.ai.supplierRec': 'Supplier Recommendation',
  'prc.ai.supplierRecDesc': 'Based on historical data, 3 quality suppliers recommended with ratings >4.5',
  'prc.recentOrders': 'Recent Orders',
  'prc.viewAll': 'View All',
  'prc.active': 'Active',
  'prc.pending': 'Pending',
  'prc.suspended': 'Suspended',
  'prc.approved': 'Approved',
  'prc.inProgress': 'In Progress',
  'prc.completed': 'Completed',
  'prc.rejected': 'Rejected',
  'prc.searchSupplier': 'Search suppliers...',
  'prc.rating': 'Rating',
  'prc.orders': 'Orders',
  'prc.highPriority': 'High Priority',
  'prc.contractsComingSoon': 'Contract Management Coming Soon',
  'prc.contractsComingSoonDesc': 'AI contract review, e-signature, compliance tracking and more features under development',

  // ---- Inventory (inv) ----
  'inv.title': 'Inventory Management',
  'inv.desc': 'Stocktaking · In/Out Management · Stock Alerts · Batch Tracking · Warehouses',
  'inv.aiRestock': 'AI Restock',
  'inv.newRecord': 'New Record',
  'inv.stat.totalSku': 'Total SKUs',
  'inv.stat.lowStockAlerts': 'Low Stock Alerts',
  'inv.stat.totalValue': 'Total Value',
  'inv.stat.turnoverRate': 'Turnover Rate',
  'inv.stat.needAttention': 'Needs Attention',
  'inv.cat.overview': 'Overview',
  'inv.cat.stockList': 'Stock List',
  'inv.cat.inOutRecords': 'In/Out Records',
  'inv.cat.warehouses': 'Warehouses',
  'inv.aiInsights': 'AI Insights',
  'inv.ai.restockAlert': 'Smart Restock Alert',
  'inv.ai.restockAlertDesc': 'MCU STM32 stock below safety level, recommend restocking 500 units immediately',
  'inv.ai.slowMoving': 'Slow-Moving Stock Alert',
  'inv.ai.slowMovingDesc': 'ESD packaging turnover days exceed 90, recommend promotion or return',
  'inv.ai.turnoverOpt': 'Turnover Optimization',
  'inv.ai.turnoverOptDesc': 'Overall turnover rate 3.8x, target 4.5x, recommend adjusting procurement rhythm',
  'inv.stockAlerts': 'Stock Alerts',
  'inv.viewAll': 'View All',
  'inv.normal': 'Normal',
  'inv.low': 'Low Stock',
  'inv.outOfStock': 'Out of Stock',
  'inv.overstock': 'Overstock',
  'inv.safetyStock': 'Safety Stock',
  'inv.searchItem': 'Search item name/SKU...',
  'inv.in': 'Inbound',
  'inv.out': 'Outbound',
  'inv.operator': 'Operator',
  'inv.warehousesComingSoon': 'Warehouse Management Coming Soon',
  'inv.warehousesComingSoonDesc': 'Multi-warehouse linkage, location management, RFID tracking and more features under development',

  // ---- Navigation (nav) ----
  'nav.procurement': 'Procurement',
  'nav.inventory': 'Inventory',
'''

# Insert before the closing marker
zh_content = zh_content.replace(
    "\n  // ---- Settings standalone extras (stg) ----\n\n}",
    zh_keys + "\n  // ---- Settings standalone extras (stg) ----\n\n}"
)
en_content = en_content.replace(
    "\n  // ---- Settings standalone extras (stg) ----\n\n}",
    en_keys + "\n  // ---- Settings standalone extras (stg) ----\n\n}"
)

open('/Users/yanyu/YYC-Cube/YYC3-Administration/src/app/locales/zh.ts', 'w', encoding='utf-8').write(zh_content)
open('/Users/yanyu/YYC-Cube/YYC3-Administration/src/app/locales/en.ts', 'w', encoding='utf-8').write(en_content)

print('Done - ZH and EN keys added')