#!/usr/bin/env python3
"""Add translation keys for channel-center, collab-creation, data-integration,
marketing-analytics, and additional tools keys to ZH and EN locale files."""

zh_keys = """
// ---- Channel Center (ch) ----
'ch.title': '渠道中心',
'ch.desc': '全渠道统一管理 · 多渠道集成 · 数据分析',
'ch.cat.overview': '概览',
'ch.cat.config': '渠道配置',
'ch.cat.sync': '数据同步',
'ch.cat.analytics': '渠道分析',
'ch.cat.operations': '运营管理',
'ch.totalChannels': '渠道总数',
'ch.allOnline': '全部在线',
'ch.todayRevenue': '今日营收',
'ch.vsYesterday': 'vs 昨日',
'ch.activeUsers': '活跃用户',
'ch.near7Days': '近 7 天',
'ch.avgROI': '平均ROI',
'ch.optimized': '已优化',
'ch.configure': '配置',
'ch.testConnection': '测试连接',
'ch.connectNow': '立即配置',
'ch.status.connected': '已连接',
'ch.status.disconnected': '未连接',
'ch.status.warning': '警告',

// ---- Collab Creation (collab) ----
'collab.title': '协同创作',
'collab.desc': '创意项目 · 创意库 · 团队协作 · AI工具 · 数据分析',
'collab.cat.projects': '创意项目',
'collab.cat.gallery': '创意库',
'collab.cat.team': '团队协作',
'collab.cat.aiTools': 'AI工具',
'collab.cat.analytics': '数据分析',
'collab.newProject': '新建项目',
'collab.submitIdea': '提交创意',
'collab.aiBrainstorm': 'AI头脑风暴',
'collab.comment': '评论',
'collab.allStatus': '全部状态',
'collab.status.active': '进行中',
'collab.status.review': '评审中',
'collab.status.done': '已完成',
'collab.totalProjects': '项目总数',
'collab.activeMembers': '活跃成员',
'collab.ideasGenerated': '创意生成',
'collab.avgScore': '平均评分',

// ---- Data Integration (di) ----
'di.title': '数据集成',
'di.desc': '企业级数据集成 · 实时CDC同步 · 数据质量保障',
'di.cat.sources': '数据源',
'di.cat.sync': '同步任务',
'di.cat.transform': '数据转换',
'di.cat.quality': '数据质量',
'di.cat.lineage': '数据血缘',
'di.cat.monitoring': '监控',
'di.configure': '配置',
'di.test': '测试',
'di.totalSources': '数据源',
'di.syncTasks': '同步任务',
'di.running': '运行中',
'di.dataThroughput': '数据吞吐',
'di.today': '今日',
'di.qualityScore': '质量评分',
'di.excellent': '优秀',
'di.status.connected': '已连接',
'di.status.disconnected': '未连接',
'di.status.error': '异常',

// ---- Marketing Analytics (ma) ----
'ma.title': '营销效果分析',
'ma.desc': '实时数据追踪 · AI智能分析 · 可视化报表',
'ma.roi': '总投资回报率',
'ma.conversion': '转化率',
'ma.acquisitionCost': '获客成本',
'ma.reachRate': '触达率',
'ma.export': '导出报表',
'ma.aiAnalyze': 'AI 分析',
'ma.timeRange.7d': '近 7 天',
'ma.timeRange.30d': '近 30 天',
'ma.timeRange.90d': '近 90 天',
'ma.channelPerformance': '渠道表现',
'ma.campaignMetrics': '活动指标',
'ma.topCampaigns': '热门活动',
'ma.campaignROI': '活动ROI',
'ma.conversions': '转化数',
'ma.budget': '预算',

// ---- Additional Tools (tools) ----
'tools.overviewStats': '概览统计',
'tools.totalTools': '工具总数',
'tools.allOnline': '全部在线',
'tools.todayExec': '今日执行',
'tools.vsYesterday': 'vs 昨日',
'tools.successRate': '成功率',
'tools.near7Days': '近 7 天',
'tools.avgTime': '平均耗时',
'tools.optimized': '已优化',
'tools.toolsReady': '{n} 工具就绪',
'tools.metrics.efficiency': '生成效率',
'tools.metrics.codeQuality': '代码质量',
'tools.metrics.coverage': '覆盖率',
'tools.metrics.bugRate': 'Bug 率',
'tools.metrics.throughput': '数据吞吐',
'tools.metrics.latency': '延迟',
'tools.metrics.errorRate': '异常率',
'tools.metrics.pipelines': '流水线',
'tools.metrics.securityScore': '安全评分',
'tools.metrics.vulnerabilities': '漏洞数',
'tools.metrics.protectionRate': '防护率',
'tools.metrics.scanCount': '扫描次数',
'tools.metrics.knowledgeNodes': '知识节点',
'tools.metrics.relevance': '关联度',
'tools.metrics.querySpeed': '查询速度',
'tools.metrics.updateFreq': '更新频率',
'tools.metrics.fps': 'FPS',
'tools.metrics.loadTime': '加载时间',
'tools.metrics.memory': '内存',
'tools.metrics.optimizations': '优化项',
'tools.metrics.storage': '存储容量',
'tools.metrics.queryPerf': '查询性能',
'tools.metrics.dataNodes': '数据节点',
'tools.metrics.batchSpeed': '批处理速度',
'tools.cap.codeGen': 'React/TS 代码生成',
'tools.cap.apiGen': 'API 接口自动生成',
'tools.cap.unitTest': '单元测试生成',
'tools.cap.refactor': '代码重构优化',
'tools.cap.docs': '文档自动生成',
'tools.cap.dataMonitor': '实时数据流监控',
'tools.cap.anomaly': '异常检测告警',
'tools.cap.trafficPredict': '流量预测分析',
'tools.cap.pipeline': '管道健康评估',
'tools.cap.autoScale': '自动扩缩容',
'tools.cap.vulnScan': '代码漏洞扫描',
'tools.cap.depAudit': '依赖安全审计',
'tools.cap.apiSecurity': 'API 安全检测',
'tools.cap.sensitiveData': '敏感数据检测',
'tools.cap.compliance': '合规性检查',
'tools.cap.knowledgeGraph': '知识图谱构建',
'tools.cap.semanticSearch': '语义搜索引擎',
'tools.cap.entityRelation': '实体关系抽取',
'tools.cap.reasoning': '知识推理引擎',
'tools.cap.qa': '自动问答系统',
'tools.cap.bottleneck': '性能瓶颈诊断',
'tools.cap.bundleAnalysis': '打包分析',
'tools.cap.memoryLeak': '内存泄漏检测',
'tools.cap.renderOptimize': '渲染优化',
'tools.cap.cacheStrategy': '缓存策略',
'tools.cap.dataWarehouse': '分布式数据存储',
'tools.cap.queryEngine': '高性能查询引擎',
'tools.cap.dataPartition': '智能数据分区',
'tools.cap.dataBackup': '自动备份恢复',
'tools.cap.dataCompress': '数据压缩优化',
'tools.result.codeGen': '已生成 3 个高质量 TypeScript React 组件，通过全部类型检查和 ESLint 规则。代码覆盖率 89%，无安全漏洞。',
'tools.result.dataFlow': '8 条数据管道运行正常，检测到 Pipeline #3 存在潜在瓶颈，已自动生成优化建议。预测未来 4 小时流量峰值为 15.2K/s。',
'tools.result.security': '全量安全扫描完成：32 文件、47 依赖包均通过检查。0 漏洞、0 敏感数据泄露，OWASP Top 10 全部合规。安全评级 A+。',
'tools.result.knowledge': '知识图谱更新完成：24.6K 节点，发现 312 个新实体关联，生成 45 条推断（准确率 94.8%）。查询延迟优化至 8ms。',
'tools.result.perf': '性能优化完成：7 项优化建议，预计可提升 30% 加载速度。内存占用减少 32MB，FPS 稳定在 60。',
'tools.result.warehouse': '数据仓库运行正常：512TB 存储容量，查询延迟 < 50ms。数据节点 128 个，批处理速度 1.2GB/s。',
"""

en_keys = """
// ---- Channel Center (ch) ----
'ch.title': 'Channel Center',
'ch.desc': 'Unified Channel Management · Multi-Channel Integration · Data Analytics',
'ch.cat.overview': 'Overview',
'ch.cat.config': 'Channel Config',
'ch.cat.sync': 'Data Sync',
'ch.cat.analytics': 'Analytics',
'ch.cat.operations': 'Operations',
'ch.totalChannels': 'Total Channels',
'ch.allOnline': 'All Online',
'ch.todayRevenue': 'Today Revenue',
'ch.vsYesterday': 'vs Yesterday',
'ch.activeUsers': 'Active Users',
'ch.near7Days': 'Last 7 Days',
'ch.avgROI': 'Average ROI',
'ch.optimized': 'Optimized',
'ch.configure': 'Configure',
'ch.testConnection': 'Test Connection',
'ch.connectNow': 'Connect Now',
'ch.status.connected': 'Connected',
'ch.status.disconnected': 'Disconnected',
'ch.status.warning': 'Warning',

// ---- Collab Creation (collab) ----
'collab.title': 'Collaboration Hub',
'collab.desc': 'Creative Projects · Gallery · Teamwork · AI Tools · Analytics',
'collab.cat.projects': 'Projects',
'collab.cat.gallery': 'Gallery',
'collab.cat.team': 'Team',
'collab.cat.aiTools': 'AI Tools',
'collab.cat.analytics': 'Analytics',
'collab.newProject': 'New Project',
'collab.submitIdea': 'Submit Idea',
'collab.aiBrainstorm': 'AI Brainstorm',
'collab.comment': 'Comment',
'collab.allStatus': 'All Status',
'collab.status.active': 'Active',
'collab.status.review': 'In Review',
'collab.status.done': 'Completed',
'collab.totalProjects': 'Total Projects',
'collab.activeMembers': 'Active Members',
'collab.ideasGenerated': 'Ideas Generated',
'collab.avgScore': 'Avg Score',

// ---- Data Integration (di) ----
'di.title': 'Data Integration',
'di.desc': 'Enterprise Data Integration · Real-time CDC · Data Quality',
'di.cat.sources': 'Data Sources',
'di.cat.sync': 'Sync Tasks',
'di.cat.transform': 'Transform',
'di.cat.quality': 'Data Quality',
'di.cat.lineage': 'Lineage',
'di.cat.monitoring': 'Monitoring',
'di.configure': 'Configure',
'di.test': 'Test',
'di.totalSources': 'Data Sources',
'di.syncTasks': 'Sync Tasks',
'di.running': 'Running',
'di.dataThroughput': 'Throughput',
'di.today': 'Today',
'di.qualityScore': 'Quality Score',
'di.excellent': 'Excellent',
'di.status.connected': 'Connected',
'di.status.disconnected': 'Disconnected',
'di.status.error': 'Error',

// ---- Marketing Analytics (ma) ----
'ma.title': 'Marketing Analytics',
'ma.desc': 'Real-time Tracking · AI Analysis · Visual Reports',
'ma.roi': 'ROI',
'ma.conversion': 'Conversion Rate',
'ma.acquisitionCost': 'Acquisition Cost',
'ma.reachRate': 'Reach Rate',
'ma.export': 'Export Report',
'ma.aiAnalyze': 'AI Analysis',
'ma.timeRange.7d': 'Last 7 Days',
'ma.timeRange.30d': 'Last 30 Days',
'ma.timeRange.90d': 'Last 90 Days',
'ma.channelPerformance': 'Channel Performance',
'ma.campaignMetrics': 'Campaign Metrics',
'ma.topCampaigns': 'Top Campaigns',
'ma.campaignROI': 'Campaign ROI',
'ma.conversions': 'Conversions',
'ma.budget': 'Budget',

// ---- Additional Tools (tools) ----
'tools.overviewStats': 'Overview Stats',
'tools.totalTools': 'Total Tools',
'tools.allOnline': 'All Online',
'tools.todayExec': 'Today Executions',
'tools.vsYesterday': 'vs Yesterday',
'tools.successRate': 'Success Rate',
'tools.near7Days': 'Last 7 Days',
'tools.avgTime': 'Avg Time',
'tools.optimized': 'Optimized',
'tools.toolsReady': '{n} Tools Ready',
'tools.metrics.efficiency': 'Efficiency',
'tools.metrics.codeQuality': 'Code Quality',
'tools.metrics.coverage': 'Coverage',
'tools.metrics.bugRate': 'Bug Rate',
'tools.metrics.throughput': 'Throughput',
'tools.metrics.latency': 'Latency',
'tools.metrics.errorRate': 'Error Rate',
'tools.metrics.pipelines': 'Pipelines',
'tools.metrics.securityScore': 'Security Score',
'tools.metrics.vulnerabilities': 'Vulnerabilities',
'tools.metrics.protectionRate': 'Protection Rate',
'tools.metrics.scanCount': 'Scan Count',
'tools.metrics.knowledgeNodes': 'Knowledge Nodes',
'tools.metrics.relevance': 'Relevance',
'tools.metrics.querySpeed': 'Query Speed',
'tools.metrics.updateFreq': 'Update Frequency',
'tools.metrics.fps': 'FPS',
'tools.metrics.loadTime': 'Load Time',
'tools.metrics.memory': 'Memory',
'tools.metrics.optimizations': 'Optimizations',
'tools.metrics.storage': 'Storage',
'tools.metrics.queryPerf': 'Query Perf',
'tools.metrics.dataNodes': 'Data Nodes',
'tools.metrics.batchSpeed': 'Batch Speed',
'tools.cap.codeGen': 'React/TS Code Gen',
'tools.cap.apiGen': 'API Auto-Generation',
'tools.cap.unitTest': 'Unit Test Generation',
'tools.cap.refactor': 'Code Refactoring',
'tools.cap.docs': 'Auto Documentation',
'tools.cap.dataMonitor': 'Real-time Data Monitor',
'tools.cap.anomaly': 'Anomaly Detection',
'tools.cap.trafficPredict': 'Traffic Prediction',
'tools.cap.pipeline': 'Pipeline Health',
'tools.cap.autoScale': 'Auto Scaling',
'tools.cap.vulnScan': 'Vulnerability Scan',
'tools.cap.depAudit': 'Dependency Audit',
'tools.cap.apiSecurity': 'API Security',
'tools.cap.sensitiveData': 'Sensitive Data Detection',
'tools.cap.compliance': 'Compliance Check',
'tools.cap.knowledgeGraph': 'Knowledge Graph',
'tools.cap.semanticSearch': 'Semantic Search',
'tools.cap.entityRelation': 'Entity Relation',
'tools.cap.reasoning': 'Reasoning Engine',
'tools.cap.qa': 'Auto Q&A',
'tools.cap.bottleneck': 'Bottleneck Diagnosis',
'tools.cap.bundleAnalysis': 'Bundle Analysis',
'tools.cap.memoryLeak': 'Memory Leak Detection',
'tools.cap.renderOptimize': 'Render Optimization',
'tools.cap.cacheStrategy': 'Cache Strategy',
'tools.cap.dataWarehouse': 'Distributed Storage',
'tools.cap.queryEngine': 'High-Perf Query Engine',
'tools.cap.dataPartition': 'Smart Partitioning',
'tools.cap.dataBackup': 'Auto Backup',
'tools.cap.dataCompress': 'Data Compression',
'tools.result.codeGen': 'Generated 3 high-quality TypeScript React components. All type checks and ESLint rules passed. 89% code coverage, zero security vulnerabilities.',
'tools.result.dataFlow': '8 data pipelines running normally. Pipeline #3 bottleneck detected with auto-generated optimization suggestions. Predicted peak traffic: 15.2K/s in next 4h.',
'tools.result.security': 'Full security scan completed: 32 files, 47 dependencies passed. 0 vulnerabilities, 0 sensitive data leaks, OWASP Top 10 compliant. Rating: A+.',
'tools.result.knowledge': 'Knowledge graph updated: 24.6K nodes, 312 new entity relations discovered, 45 inferences generated (94.8% accuracy). Query latency optimized to 8ms.',
'tools.result.perf': 'Performance optimization complete: 7 suggestions, estimated 30% load speed improvement. 32MB memory reduction, stable 60 FPS.',
'tools.result.warehouse': 'Data warehouse running normally: 512TB storage, query latency < 50ms. 128 data nodes, 1.2GB/s batch processing speed.',
"""


for locale, keys_text in [('zh', zh_keys), ('en', en_keys)]:
    path = f'/Users/yanyu/YYC-Cube/YYC3-Administration/src/app/locales/{locale}.ts'
    content = open(path).read()

    # Find the last '}' before the export
    # Insert keys before the closing '};' of the locale object
    insert_marker = '  // ---- Navigation'

    # Find lines that are not already present
    new_keys = []
    for line in keys_text.strip().split('\n'):
        stripped = line.strip()
        if stripped and not stripped.startswith('//') and ':' in stripped:
            key_part = stripped.split(':')[0].strip().strip("'")
            if key_part not in content:
                new_keys.append(line)

    if new_keys:
        insert_text = '\n' + '\n'.join(new_keys) + '\n'
        content = content.replace(insert_marker, insert_text + insert_marker)
        open(path, 'w').write(content)
        print(f'{locale}.ts: Added {len(new_keys)} keys')
    else:
        print(f'{locale}.ts: No new keys needed')

print('Done!')
